In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Read the data
prior_data = pd.read_csv('phone_prior.csv')
conditional_data = pd.read_csv('phone_conditional.csv')

In [11]:
import numpy as np
import csv

def read_csv(filename):
    with open(filename, 'r') as f:
        return np.array([list(map(float, row)) for row in csv.reader(f)])

def calculate_posterior_probabilities(prior, conditional):
    joint_probability = prior * conditional
    p_two_bars = np.sum(joint_probability)
    posterior = joint_probability / p_two_bars
    return posterior

def write_csv(filename, data):
    with open(filename, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(data)

def main():
    # Read data from CSV files
    prior = read_csv('phone_prior.csv')
    conditional = read_csv('phone_conditional.csv')
    
    # Calculate posterior probabilities
    posterior = calculate_posterior_probabilities(prior, conditional)
    posterior = np.round(posterior, 3)
    
    # Write results to CSV file
    write_csv('posterior.csv', posterior)
    
    # Print results to console
    print("Posterior probabilities:")
    print(posterior)
    
    # Verify that probabilities sum to 1
    total_probability = np.sum(posterior)
    print(f"\nSum of all probabilities: {total_probability:.6f}")

if __name__ == "__main__":
    main()

Posterior probabilities:
[[0.074 0.188 0.074 0.005]
 [0.005 0.149 0.094 0.074]
 [0.001 0.005 0.149 0.094]
 [0.001 0.001 0.01  0.074]]

Sum of all probabilities: 0.998000
